version: "3.7"
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: password
      DB_DRIVER: org.postgresql.Driver
      DB_URL: jdbc:postgresql://postgres:5432/db
      WAIT_FOR: postgres:5432
    networks:
      - nw
  postgres:
    #   Use the Docker Image postgres. This will pull the newest release.
    image: "postgres:11-alpine"
    #   Give the container the name my_postgres. You can changes to something else.
    container_name: "library"
    #   Setup the username, password, and database name. You can changes these values.
    environment:
      - POSTGRES_USER: test_user
      - POSTGRES_PASSWORD: password
      - POSTGRES_DB: test_db
    #   Maps port 5442 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "5442:5432"
    #   Set a volume some that database is not lost after shutting down the container.
    #   I used the name postgres-data but you can changed it to something else.
    volumes:
      - ./postgres-data:/var/lib/debug/postgresql/data
    networks:
      - nw
networks:
  nw: